### ISSUE TITLE
global.json

### ISSUE THREAD

**Issue by asulwer** [asulwer/RulesEngine#13]
i do not see why this file is necessary.  if i am not mistaken it is not being used (project targets netstandard2.1 not Net Core 3.1+) and if it is it appears pointless [global.json file allows you to define which .NET SDK version is used when you run .NET CLI commands](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json)

i am creating a PR with its removal

**Comment by RenanCarlosPereira** [comment]
the tests projects were using it, its targeting dotnet 8, its a good idea to maintain this file there
