### ISSUE TITLE
updating dotnetcore-build.yml workflow

### ISSUE THREAD

**Issue by asulwer** [asulwer/RulesEngine#19]
there exist a couple of issues, that were previously fixed, that need to be addressed with the workflow.  i suggest a PR with the following changes made.  but first lets discuss?

1. Generate Report and Check Coverage scripts should be removed and their functionality moved to the workflow directly
2. filename and workflow name do not match
3. runs-on set to default of ubuntu-latest, i want to change to windows
4. actions/checkout@v3 is deprecated and should be updated to v4
5. dotnet-version changed from 6 to 8
6. Coveralls Github Action will fail, we do not have a GITHUB_TOKEN setup

**Comment by asulwer** [comment]
move check-coverage.ps1 into dotnetcore-build.yml

**Comment by asulwer** [comment]
remove scripts & config folders, functionality in them have been moved to dotnetcore-build.yml

**Comment by RenanCarlosPereira** [comment]
I have a couple of questions for the topics: 

**1. Generate Report and Check Coverage scripts should be removed and their functionality moved to the workflow directly**
> Why do we need to move the coverage to the workflow, if we do that we will depend on a task that we don't need. and I won't be able to run the script without depending on Github's actions. 

**2. filename and workflow name do not match**
> We can change it, but it's not a big deal. 
    
**3. runs-on set to default of ubuntu-latest, I want to change to windows.**
> Using Linux runners for GitHub Actions is cheaper than using Windows runners, as the cost per minute for Linux is half that of Windows. This cost difference can add up significantly over time, especially for large projects or those with frequent builds and tests.
Linux: $0.008 per minute
Windows: $0.016 per minute
    
**6. Coveralls Github Action will fail, we do not have a GITHUB_TOKEN setup.**
> The GITHUB_TOKEN is automatically generated by GitHub for each workflow run and is available to use within your GitHub Actions workflows. You do not need to create it manually. Here's how you can access and use it in your workflow:

**Comment by asulwer** [comment]
i was incorrect about the github_token issue.

**Comment by asulwer** [comment]
moving report generation and code coverage rely on each other, move one move both.  simply for code consolidation.  hunting to understand code shouldn't exist, simple and concise and possible.  after what the original author stated its purpose was used for convinces me that it should be removed entirely but i am willing to keep it.  i want to make it easier to find and change/update

**Comment by asulwer** [comment]
are we paying those fees for windows vs linux?  i understand linux is generically better at hardware management than other OS's out there.  does the workflow run faster on linux vs windows? that would convince me.  it really doesnt matter what the answer to this question is, really it doesn't need to be changed.  i just wanted to understand mostly the why for things.

**Comment by RenanCarlosPereira** [comment]
We have 2000 free minutes each month on GitHub Actions. Running on Linux is cheaper, costing less per minute compared to Windows. This means we can get more build time on Linux within our free tier. Hence, we'll have fewer hours if we use Windows runners.

For more info, check out GitHub's billing details [here](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions).

**Comment by asulwer** [comment]
oh nice!  then lets keep it as linux.
