### ISSUE TITLE
Pull request into main branch

### ISSUE THREAD

**Issue by RenanCarlosPereira** [asulwer/RulesEngine#2]
Hi @asulwer,

I've noticed that you have been actively pushing commits to the main branch of your forked repository without using pull requests. Since our project heavily relies on the rules engine library, it’s crucial for us to maintain a clear and documented development process.

To ensure transparency and enable us to track the reasons behind specific implementations, I suggest we start using pull requests for all changes. This will help us identify bugs more effectively and understand the rationale behind each change.

If you're open to this, we can collaborate to make this fork more robust and maintainable. Otherwise, we may need to consider maintaining our own separate fork.

Please let me know your thoughts.

Thanks,

**Comment by asulwer** [comment]
excellent idea.  i will do this moving forward.

**Comment by RenanCarlosPereira** [comment]
@asulwer could you add me as a collaborator in this repo?
