### ISSUE TITLE
remove deprecated code and formatting issues

### ISSUE THREAD

**Issue by asulwer** [asulwer/RulesEngine#25]
really just beautification of the code needs to be done

**Comment by asulwer** [comment]
remove deprecated methods and such

**Comment by RenanCarlosPereira** [comment]
formatting the code is fine, please open a PR with only formatting issues, you can use the codeMaid to do it if you are using Visual Studio. 

https://marketplace.visualstudio.com/items?itemName=SteveCadwallader.CodeMaidVS2022

notice that rules engine has a file to define how the code should look like in an .editorconfig.

https://github.com/asulwer/RulesEngine/blob/main/.editorconfig

**Comment by asulwer** [comment]
i did see editorconfig but is that honored by VS or VSCode?  i couldnt find out how to get that working with VS Enterprise or Pro, maybe community?

**Comment by RenanCarlosPereira** [comment]
1. **VS Code:** Make sure you have the EditorConfig extension installed from the marketplace.
2. **Visual Studio:** EditorConfig is supported natively, but ensure it's enabled in Tools > Options > Text Editor > General.

Check [Microsoft's documentation on EditorConfig](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options) for detailed guidance.

that should be loaded automatically.

**Comment by RenanCarlosPereira** [comment]
cleaning up the project Demo #34

**Comment by asulwer** [comment]
i couldn't find that documentation for VS, thanks for that.
