### ISSUE TITLE
Enable Dependabot for Automatic Dependency Updates

### ISSUE THREAD

**Issue by RenanCarlosPereira** [asulwer/RulesEngine#33]
Can you enable Dependabot for this repo? It helps keep dependencies up-to-date automatically, which improves security and stability.

**Why Dependabot is Important:**
1. **Automated Updates:** Dependabot regularly checks for updates to the dependencies used in the project and creates pull requests to update them.
2. **Improved Security:** By keeping dependencies updated, we can reduce vulnerabilities in our codebase.
3. **Stability and Compatibility:** Regular updates ensure that we are using the most stable and compatible versions of dependencies.
4. **Reduced Maintenance Effort:** Dependabot handles the tedious task of tracking and updating dependencies, freeing up time for other development tasks.

Dependabot was enabled in the main fork, so we need to enable it here too to maintain consistency and security.

**How to Enable:**
1. Go to the repo's "Settings".
2. Under "Security & analysis", find "Dependabot".
3. Click "Enable Dependabot".

For more details, check out the [Dependabot Quickstart Guide](https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide).
note that we already have a file configured. 
https://github.com/asulwer/RulesEngine/blob/main/.github/dependabot.yml

Thanks!

**Comment by asulwer** [comment]
enabling this should solve this [issue](https://github.com/asulwer/RulesEngine/issues/20)

**Comment by asulwer** [comment]
enabled
