### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by asulwer** [asulwer/RulesEngine#42]
@RenanCarlosPereira 

publish a new release and nuget package?  are we ready for it?

**Comment by RenanCarlosPereira** [comment]
No, we need to update the changelog with the fixes we have fixed

I will open the PR for the changelog.

We also need to define the package name 😅


We also need to generate another sign key. We can keep the same file name just generate another one and update the references in the manifests

**Comment by asulwer** [comment]
are you creating a PR to update the changelog AND signkey?

**Comment by RenanCarlosPereira** [comment]
No just the changelog, if you want to do the sign key feel free, too late here today, will catch up tomorrow

**Comment by asulwer** [comment]
no problem

**Comment by RenanCarlosPereira** [comment]
In case you dont know how to generate the base64 and import it to the secrets heres how to do it

In the end ipen the file copy its contents and add to the secret in github


```powershell
# Generate the .snk file using sn.exe
# Make sure the Developer Command Prompt for Visual Studio is available
& "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.29.30037\bin\Hostx64\x64\sn.exe" -k RulesEngine-publicKey.snk

# Convert the .snk file to a base64 string
$snkPath = "RulesEngine-publicKey.snk"
$base64String = [Convert]::ToBase64String([IO.File]::ReadAllBytes($snkPath))

# Output the base64 string to a file
$base64String > "RulesEngine-publicKey.txt"

# Also print the base64 string to the console
Write-Output $base64String
```

### Explanation
1. **Generate the .snk file**: This uses the `sn.exe` tool to create a new strong-name key file (`RulesEngine-publicKey.snk`).
2. **Convert to Base64**: This reads the `.snk` file and converts its content to a base64-encoded string.
3. **Output the Base64 String**: The script writes the base64 string to a file (`RulesEngine-publicKey.txt`) and prints it to the console.

### Usage
- Make sure to update the path to `sn.exe` if it differs based on your Visual Studio installation.
- Run this script in a PowerShell environment.

**Comment by asulwer** [comment]
completed

**Comment by asulwer** [comment]
v6.0.0 published to nuget and package created for github

**Comment by asulwer** [comment]
NOW! lets make some changes and break this thing! JK

**Comment by RenanCarlosPereira** [comment]
nice, all good with the automation?

**Comment by RenanCarlosPereira** [comment]
I noticed you created, the release resources, you don't need to do it, just create the tag when the build complete it will generate a release automatically, so u only need to add some text there if needed

**Comment by asulwer** [comment]
i couldn't figure out how to create only a tag.

**Comment by RenanCarlosPereira** [comment]
oh no, what I mean is, that you don't need to attach binaries, the pipeline will do that for you.
if you see we will have 2 binaries there, there no need 😅

**Comment by asulwer** [comment]
i had to create a release to create the tag.  i think creating it as prerelease to create the tag and deleting the prerelease was an option i saw someone mention in the community

**Comment by RenanCarlosPereira** [comment]
Yes, you can create a tag in GitHub without creating a release.
 Here’s how you can create a tag without a release using Git commands.

### Using Git Command Line:

1. Open your terminal or command prompt.
2. Navigate to your local repository.
3. Create a tag using the following command:

   ```bash
   git tag <tag-name>
   ```

   For example, to create a tag named `v1.0.0`, you would use:

   ```bash
   git tag v1.0.0
   ```

4. Push the tag to GitHub:

   ```bash
   git push origin <tag-name>
   ```

   For example:

   ```bash
   git push origin v1.0.0
   ```

This will create a tag in your repository without creating a release. You can see the tags in the "Tags" section of your repository on GitHub.

that will trigger the release and build and publish the nuget.
when everything is ready you can edit the release with some notes. you can also create in github too, but you don't need to add the artefacts

**Comment by asulwer** [comment]
thanks!
