### ISSUE TITLE
myValue' not found"

### ISSUE THREAD

**Issue by sunil233** [asulwer/RulesEngine#45]
Exception while parsing expression `myValue.Value1 == \"Fabrikam\"` - Type 'myValue' not found"

**Comment by asulwer** [comment]
is this in a project you are working on?  or?

**Comment by RenanCarlosPereira** [comment]
Hey @sunil233 could you provide the full sample, we need to check what you are passing in the parameters for the rules engine method, thanks 🙏

**Comment by asulwer** [comment]
@sunil233 found the issue, opened a PR with the solution.  waiting on it to be reviewed before merging

**Comment by asulwer** [comment]
@RenanCarlosPereira check PR

**Comment by RenanCarlosPereira** [comment]
Oh ok, I didnt k ow he was referring to the demo code 😂

**Comment by asulwer** [comment]
i assumed he was because that line exists in that code AND it was an issue
