### ISSUE TITLE
Move to Central Package Management (CPM)

### ISSUE THREAD

**Issue by HalvorNygaard** [asulwer/RulesEngine#69]
Could consider to move over to CPM. This way all the dependency versioning would be managed from one file (Directory.Packages.props) on solution root. Since the projects in the solution don't have that many overlapping dependencies its not that big of a deal, but its kind of nice either way.

https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management

**Comment by HalvorNygaard** [comment]
I do have the changes changes necessary in a local branch, could push them up if i get access.

This test seem to fail for the branch, but it also fails on main:
RulesEngineWithGlobalParam_RunsSuccessfully(ruleFileName: "rules11.json")

**Comment by asulwer** [comment]
@HalvorNygaard we are using github to centrally manage dependencies.  in my opinion, it doesn't seem to be working as expected though.  @RenanCarlosPereira is more familiar with dependabot

@HalvorNygaard this suggestion would be useful if we used the same dependencies across projects.  typically i use the solution explorer to manage dependencies for all of the projects.  in my opinion this serves the same purpose.

**Comment by asulwer** [comment]
@HalvorNygaard here is the [dependabot](https://github.com/asulwer/RulesEngine/edit/main/.github/dependabot.yml) in question that updates packages.  @RenanCarlosPereira it appears it is not updating nuget packages?  should we enable this?

**Comment by RenanCarlosPereira** [comment]
yes that should be enabled
