### ISSUE TITLE
Changes to Project Structure

### ISSUE THREAD

**Issue by RenanCarlosPereira** [asulwer/RulesEngine#7]
@asulwer 

I noticed that in your fork of the repository, the `src` and `tests` folders have been removed, and their contents have been moved to the root directory. This deviates from the standard project structure recommended by several authoritative sources.

**Details:**
The standard project structure, which includes dedicated `src` and `tests` folders, is beneficial for maintaining a clean and organized codebase. This structure is recommended for several reasons:
- **Separation of Concerns:** Keeps source code and test code organized separately, improving readability and maintainability.
- **Scalability:** Helps in managing large codebases more efficiently by clearly delineating different parts of the project.

**References:**
1. **Microsoft Project Structure Guidelines:** Microsoft recommends maintaining a clear project structure with separate directories for source code and tests. More details can be found here: [Microsoft Project Structure](https://learn.microsoft.com/en-us/dotnet/core/porting/project-structure).
2. **Open Source Project Structure Conventions:** The open-source community also supports this structure. For example, the following GitHub repository provides guidelines and examples: [Folder Structure Conventions](https://github.com/kriasoft/Folder-Structure-Conventions).

**Question:**
Could you please provide the rationale behind removing the `src` and `tests` folders and moving their contents to the root directory? Understanding your reasoning could help align our practices or identify areas for improvement.

could we change it back?

**Comment by asulwer** [comment]
i was not aware of these porting 'guidelines' because i have not ported any projects. 

although i did find [this](https://gist.github.com/davidfowl/ed7564297c61fe9ab814) which may be a better reference than Microsoft's?

**Comment by asulwer** [comment]
i am going to update the changelog to include these guidelines, thoughts on that change?

**Comment by RenanCarlosPereira** [comment]
I dont think it needed to be added, because the original project was already like that, but you can add in the documentation on how to contribute

**Comment by asulwer** [comment]
i will consider this closed then.  if you have any concerns relating to this issue i can reopen it, assuming reopening is possible
